# This is a basic workflow to help you get started with Actions

name: Jupyter

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  schedule:
    - cron: '0 */24 * * *'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - id: repo 
        name: Repo Checkout
        uses: actions/checkout@v2

      - id: python
        name: Python Setup & Packages Installation
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'
          cache: 'pip'
      - run: pip install -r requirements.txt

      - id: jupyter 
        name: Jupyter Notebook Execution
        run: jupyter execute main.ipynb
        shell: bash
        env:
          gemini_api_key: ${{ secrets.GEMINI_API_KEY }}
          pixabay_api_key: ${{ secrets.PIXABAY_API_KEY }}
          wordpress_username: ${{ secrets.WORDPRESS_USERNAME }}
          wordpress_password: ${{ secrets.WORDPRESS_PASSWORD }}
          wordpress_client_id: ${{ secrets.WORDPRESS_CLIENT_ID }}
          wordpress_client_secret: ${{ secrets.WORDPRESS_CLIENT_SECRET }}
          reddit_client_id: ${{ secrets.REDDIT_CLIENT_ID }}
          reddit_client_secret: ${{ secrets.REDDIT_CLIENT_SECRET }}
          reddit_user_agent: ${{ secrets.REDDIT_USER_AGENT }}
          reddit_username: ${{ secrets.REDDIT_USERNAME }}
          reddit_password: ${{ secrets.REDDIT_PASSWORD }}

 # Add new files in folder, commit along with other modified files, push
#     - id: commit
#      name: Commit files
#        run:
#          git config --local user.name actions-user

#          git config --local user.email "actions@github.com"

#          git add *

#          git commit -am "GH ACTION Headlines $(date)"

#          git push origin main

#        env:
#          REPO_KEY: ${{secrets.GITHUB_TOKEN}}

#          username: github-actions
